### ISSUE TITLE
О подменах

### ISSUE THREAD

**Issue by vstakhov** [lapshinmr/samomes#4]
Как раз тут размышлял, что неплохо бы еще добавить такой компонент как подмены воды. В это очень хорошо вписывается dH/kH буферы, либо готовые, либо на базе самомеса (это как раз преусловутый гипс/хлористый кальций). Отличие в том, что из аквариума извлекается некий % воды с растворенными в ней веществами, и вносится такой же процент воды, но уже с другими концентрациями.
Например, тут можно также добавить известные концентрации ионов в подменной воде. Пока не знаю, как это четко формализовать, пока что получается довольно сложная задача, мне бы хватило отдельного виджета для реминерализации осмоса либо водопроводом, либо буферным раствором по target KH/dH.

**Comment by lapshinmr** [comment]
Т.е. хотелось бы следующее: известно kH/gH в аквариуме. Вопрос, сколько нужно добавить реминирализатора, чтобы сделать в аквариумен определенный kH/gH при заданном проценте подмены? Правильно я понял? Или какой будет kH/gH если добавить такую-то воду. Так?

**Comment by lapshinmr** [comment]
Есть идея как это сделать. В короткой и развернутой версии.

**Comment by lapshinmr** [comment]
Хотел сделать для реминерализации осмоса. А получилось сделать динамику макро элементов :-) Пока что первая версия, но уже можно поиграться.

![Screenshot from 2020-05-12 23-34-06](https://user-images.githubusercontent.com/17162919/81737507-4074c600-94a9-11ea-8de8-66094ea44db9.png)

Или сюда для осмоса сделаю, или отдельной страницей. Не решил пока.

**Comment by lapshinmr** [comment]
Решено. На странице "реминерализация" можно делать все что угодно с параметрами гш/кш.
